// Soru ve cevaplar için model sınıfı
class Question {
  final int id;
  final String question;
  final List<String> options;
  final int correctAnswerIndex;
  final String explanation;

  Question({
    required this.id,
    required this.question,
    required this.options,
    required this.correctAnswerIndex,
    required this.explanation,
  });
}

// Quiz verilerimiz
List<Question> quizQuestions = [
  Question(
    id: 1,
    question: 'Türkiye\'nin başkenti neresidir?',
    options: ['İstanbul', 'Ankara', 'İzmir', 'Bursa', 'Antalya'],
    correctAnswerIndex: 1,
    explanation: 'Ankara, Türkiye Cumhuriyeti\'nin başkentidir.',
  ),
  Question(
    id: 2,
    question: 'Dünyanın en büyük okyanusu hangisidir?',
    options: ['Atlantik', 'Hint', 'Pasifik', 'Kutup', 'Akdeniz'],
    correctAnswerIndex: 2,
    explanation: 'Pasifik Okyanusu, dünyanın en büyük okyanusu.',
  ),
  Question(
    id: 3,
    question: '2 + 2 kaçtır?',
    options: ['2', '3', '4', '5', '6'],
    correctAnswerIndex: 2,
    explanation: '2 + 2 = 4\'tür.',
  ),
  Question(
    id: 4,
    question: 'Işık hızı kaç km/s\'dir?',
    options: ['100.000', '200.000', '300.000', '400.000', '500.000'],
    correctAnswerIndex: 2,
    explanation: 'Işık hızı yaklaşık 300.000 km/s\'dir.',
  ),
  Question(
    id: 5,
    question: 'En uzun nehir hangisidir?',
    options: ['Nil', 'Amazon', 'Yangtze', 'Mississippi', 'Volga'],
    correctAnswerIndex: 0,
    explanation: 'Nil Nehri, dünyanın en uzun nehri olarak kabul edilir.',
  ),
  Question(
    id: 6,
    question: 'Kaç gezegen vardır?',
    options: ['7', '8', '9', '10', '11'],
    correctAnswerIndex: 1,
    explanation: 'Güneş Sistemi\'nde 8 gezegen bulunmaktadır.',
  ),
  Question(
    id: 7,
    question: 'Hangi element kimyasal sembolü Au\'dur?',
    options: ['Gümüş', 'Bakır', 'Altın', 'Alüminyum', 'Arsen'],
    correctAnswerIndex: 2,
    explanation: 'Altın\'ın kimyasal sembolü Au\'dur.',
  ),
  Question(
    id: 8,
    question: 'Fransa\'nın başkenti neresidir?',
    options: ['Lyon', 'Marseille', 'Paris', 'Nice', 'Toulouse'],
    correctAnswerIndex: 2,
    explanation: 'Paris, Fransa\'nın başkenti ve en büyük şehridir.',
  ),
  Question(
    id: 9,
    question: 'Shakespeare hangi ülkede doğdu?',
    options: ['ABD', 'İrlanda', 'İngiltere', 'İskoçya', 'Galler'],
    correctAnswerIndex: 2,
    explanation: 'William Shakespeare, İngiltere\'de doğdu.',
  ),
  Question(
    id: 10,
    question: 'Dünyanın en yüksek dağı hangisidir?',
    options: ['Kilimanjaro', 'Elbrus', 'Denali', 'Everest', 'Kangchenjunga'],
    correctAnswerIndex: 3,
    explanation: 'Everest, dünyanın en yüksek dağıdır.',
  ),
];
